import org from './obj_org.js'
import category from './obj_category.js'
import skill from './obj_skill.js'
import license from './obj_license.js'

export default [
  {
    date: new Date('2026-06-06'),
    org: org.rama,
    name: 'Teyin',
    category: category.androidApp,
    preview: 'https://github.com/rama-io/teyin/raw/master/docs/img/teyin_header_1200x630.svg',
    screenshots: [
      'https://raw.githubusercontent.com/rama-io/teyin/master/fastlane/metadata/android/en-US/images/phoneScreenshots/1.png',
      'https://raw.githubusercontent.com/rama-io/teyin/master/fastlane/metadata/android/en-US/images/phoneScreenshots/2.png',
      'https://raw.githubusercontent.com/rama-io/teyin/master/fastlane/metadata/android/en-US/images/phoneScreenshots/3.png',
    ],
    tags: [skill.kotlin],
    description: [
      '[p](**Teyin** is a lightweight, privacy-first **File manager** designed for speed, and simplicity.)',
      '[p](Built entirely in native **Kotlin**, Teyin runs fully **on-device** and avoids tracking.)',
    ],
    link: {
      web: 'https://rama-io.github.io/teyin.html',
      github: 'https://github.com/rama-io/teyin',
      fdroid: 'https://f-droid.org/app/com.rama.teyin',
      obtanium:
        'https://apps.obtainium.imranr.dev/redirect?r=obtainium://add/https://github.com/rama-io/teyin',
    },
    license: license.gplv3,
  },
  {
    date: new Date('2026-04-25'),
    org: org.rama,
    name: 'Tūī',
    category: category.androidApp,
    preview:
      'https://raw.githubusercontent.com/rama-io/tui/master/docs/img/tui_header_1200x630.svg',
    screenshots: [
      'https://raw.githubusercontent.com/rama-io/tui/master/fastlane/metadata/android/en-US/images/phoneScreenshots/1.png',
      'https://raw.githubusercontent.com/rama-io/tui/master/fastlane/metadata/android/en-US/images/phoneScreenshots/2.png',
      'https://raw.githubusercontent.com/rama-io/tui/master/fastlane/metadata/android/en-US/images/phoneScreenshots/3.png',
    ],
    tags: [skill.kotlin],
    description: [
      '[p](**Tūī** is a minimal, privacy-first **local music player** that skips metadata entirely. What you see is exactly what you name, no hidden tags, no surprises.)',
      '[p](Built entirely in native **Kotlin**, Tūī runs fully **on-device**, avoids tracking, no internet access, and no external APIs.)',
    ],
    link: {
      web: 'https://rama-io.github.io/tui.html',
      youtube: 'https://www.youtube.com/watch?v=We8xXVLiVI4',
      github: 'https://github.com/rama-io/tui',
      fdroid: 'https://f-droid.org/app/com.rama.tui',
      obtanium:
        'https://apps.obtainium.imranr.dev/redirect?r=obtainium://add/https://github.com/rama-io/tui',
    },
    license: license.gplv3,
  },
  {
    date: new Date('2026-03-07'),
    org: org.rama,
    name: 'Txori',
    category: category.androidApp,
    preview:
      'https://raw.githubusercontent.com/rama-io/txori/main/docs/img/txori_header_1280x630.svg',
    screenshots: [
      'https://raw.githubusercontent.com/rama-io/tui/master/fastlane/metadata/android/en-US/images/phoneScreenshots/1.png',
      'https://raw.githubusercontent.com/rama-io/tui/master/fastlane/metadata/android/en-US/images/phoneScreenshots/2.png',
      'https://raw.githubusercontent.com/rama-io/tui/master/fastlane/metadata/android/en-US/images/phoneScreenshots/3.png',
    ],
    tags: [skill.kotlin],
    description: [
      '[p](**Txori** is a minimal, privacy-first **focus session app** designed to help you stay present and intentional with your time.)',
      '[p](Built entirely in native **Kotlin**, Txori runs fully **on-device**, avoids tracking, no internet access, and no external APIs.)',
    ],
    link: {
      web: 'https://rama-io.github.io/txori.html',
      github: 'https://github.com/rama-io/txori',
      fdroid: 'https://f-droid.org/app/com.rama.txori',
      obtanium:
        'https://apps.obtainium.imranr.dev/redirect?r=obtainium://add/https://github.com/rama-io/txori',
    },
    license: license.gplv3,
  },
  {
    date: new Date('2025-12-19'),
    org: org.rama,
    name: 'Mako',
    category: category.androidApp,
    preview:
      'https://raw.githubusercontent.com/rama-io/mako/master/docs/img/mako_header_1200x630.svg',
    screenshots: [
      'https://raw.githubusercontent.com/rama-io/mako/master/fastlane/metadata/android/en-US/images/phoneScreenshots/1.png',
      'https://raw.githubusercontent.com/rama-io/mako/master/fastlane/metadata/android/en-US/images/phoneScreenshots/2.png',
      'https://raw.githubusercontent.com/rama-io/mako/master/fastlane/metadata/android/en-US/images/phoneScreenshots/3.png',
    ],
    tags: [skill.kotlin],
    description: [
      '[p](**Mako** is a minimal, privacy-first **android launcher** designed for focus, speed, and simplicity.)',
      '[p](Built entirely in native **Kotlin**, Mako runs fully **on-device**, avoids tracking, and keeps distractions to a minimum by emphasizing clarity and intentional interaction.)',
    ],
    link: {
      web: 'https://rama-io.github.io/mako.html',
      github: 'https://github.com/rama-io/mako',
      fdroid: 'https://f-droid.org/app/com.rama.mako',
      obtanium:
        'https://apps.obtainium.imranr.dev/redirect?r=obtainium://add/https://github.com/rama-io/mako',
    },
    license: license.gplv3,
  },
  {
    date: new Date('2025-11-20'),
    org: org.rama,
    name: 'Salishan',
    category: category.website,
    preview:
      'https://raw.githubusercontent.com/salishan/salishan.github.io/master/metadata/mobile.webp',
    tags: [skill.webComponents, skill.css, skill.js],
    description: [
      '[p](**Salishan** is a **keyboard layout** for Salishan and neighboring Indigenous languages of the Pacific Northwest. It extends the standard English keyboard with dead keys for glottalization, acute accent, tilde, and other diacritics, enabling efficient typing of ejective, glottalized, and lateral consonants, as well as special vowels used across multiple Salishan languages. The layout also includes combining diacritics for rare tonal or phonetic markings, making it a comprehensive tool for linguists, language learners, and community members.)',
    ],
    link: {
      web: 'https://salishan.github.io',
      github: 'https://github.com/salishan/salishan.github.io',
    },
    license: license.gplv3,
  },
  // {
  //   date: new Date('2024-12-24'),
  //   org: org.rama,
  //   name: 'LoM DB',
  //   category: category.website,
  //   preview: 'https://lomdb.github.io/img/svg/lom_header-draco.svg',
  //   screenshots: [
  //     'https://raw.githubusercontent.com/lomdb/lomdb.github.io/master/metadata/0-min.webp',
  //     'https://raw.githubusercontent.com/lomdb/lomdb.github.io/master/metadata/1-min.webp',
  //     'https://raw.githubusercontent.com/lomdb/lomdb.github.io/master/metadata/2-min.webp',
  //   ],
  //   tags: [skill.webComponents, skill.svg, skill.css, skill.three, skill.js],
  //   description: [
  //     '[p](**LoM DB** is a community-driven database for tracking and exploring merged servers, top players, and timelines across regions.)',
  //     '[p](This project is built to help players, analysts, and enthusiasts get a clearer view of evolving server data, elite players, and historical merges, all in one place.)',
  //   ],
  //   link: {
  //     web: 'https://lomdb.github.io/',
  //     github: 'https://github.com/lomdb/lomdb.github.io',
  //   },
  //   license: license.gplv3,
  // },
  {
    date: new Date('2022-09-01'), //TODO
    org: org.teamup,
    name: 'Consumer App',
    category: category.webApp,
    // preview: '',
    // screenshots: [],
    tags: [skill.vue3, skill.unoCss, skill.storybook, skill.js],
    // description: ['[p]()', '[p]()'],
    license: license.propietary,
  },
  {
    date: new Date('2022-09-01'), //TODO
    org: org.teamup,
    name: 'Provider App',
    category: category.webApp,
    // preview: '',
    // screenshots: [],
    tags: [skill.vue3, skill.unoCss, skill.storybook, skill.js],
    // description: ['[p]()', '[p]()'],
    license: license.propietary,
  },
  {
    date: new Date('2022-09-01'), //TODO
    org: org.teamup,
    name: 'DaysmartVueComponents',
    category: category.nodeModule,
    // preview: '',
    // screenshots: [],
    tags: [skill.vue3, skill.webComponents, skill.unoCss, skill.storybook, skill.vitest, skill.js],
    // description: ['[p]()', '[p]()'],
    license: license.propietary,
  },
  {
    date: new Date('2018-09-04'),
    org: org.enovational,
    name: 'Formability',
    category: category.webApp,
    // preview: '',
    // screenshots: [],
    tags: [
      skill.vue2,
      skill.rails,
      skill.scss,
      skill.typescript,
      skill.bootstrap,
      skill.konva,
      skill.jQuery,
      skill.js,
    ],
    // description: ['[p]()', '[p]()'],
    link: {
      web: 'https://formability.com',
    },
    license: license.propietary,
  },
  {
    date: new Date('2020-05-05'),
    org: org.enovational,
    name: 'Popkern',
    category: category.nodeModule,
    // preview: '',
    // screenshots: [],
    tags: [skill.vue2, skill.rails, skill.scss, skill.js, skill.three],
    // description: ['[p]()', '[p]()'],
    license: license.propietary,
  },
  // {
  //   date: new Date('2018-03-01'), //TODO
  //   org: org.enovational,
  //   name: 'Maryland Department of Transportation - MDOT',
  //   category: category.webApp,
  //   // preview: '',
  //   // screenshots: [],
  //   tags: [skill.bootstrap, skill.rails, skill.scss, skill.jQuery, skill.js],
  //   // description: ['[p]()', '[p]()'],
  //   license: license.propietary,
  // },
  {
    date: new Date('2018-05-01'),
    org: org.enovational,
    name: 'MDA Vetboard Portal',
    category: category.webApp,
    // preview: '',
    // screenshots: [],
    tags: [skill.bootstrap, skill.rails, skill.scss, skill.jQuery, skill.js],
    // description: ['[p]()', '[p]()'],
    license: license.propietary,
  },
  {
    date: new Date('2019-01-02'), //TODO
    org: org.enovational,
    name: 'MSEC Financial Disclosures Portal',
    category: category.webApp,
    // preview: '',
    // screenshots: [],
    tags: [skill.bootstrap, skill.rails, skill.scss, skill.jQuery, skill.js],
    // description: ['[p]()', '[p]()'],
    link: {
      web: 'https://efds.ethics.maryland.gov/',
    },
    license: license.propietary,
  },
  {
    date: new Date('2018-06-25'),
    org: org.enovational,
    name: 'Maryland OneStop',
    category: category.webApp,
    // preview: '',
    // screenshots: [],
    tags: [skill.bootstrap, skill.rails, skill.scss, skill.jQuery, skill.js],
    // description: ['[p]()', '[p]()'],
    link: {
      web: 'https://onestop.md.gov/',
    },
    license: license.propietary,
  },
  {
    date: new Date('2017-12-01'),
    org: org.plantTherapy,
    name: '25 Days of Christmas',
    category: category.landingPage,
    // preview: '',
    // screenshots: [],
    tags: [skill.html, skill.css, skill.jQuery, skill.js],
    // description: ['[p]()', '[p]()'],
    license: license.propietary,
  },
  {
    date: new Date('2017-08-24'),
    org: org.plantTherapy,
    name: 'Chakras',
    category: category.landingPage,
    // preview: '',
    // screenshots: [],
    tags: [skill.html, skill.css, skill.jQuery, skill.js],
    // description: ['[p]()', '[p]()'],
    license: license.propietary,
  },
  {
    date: new Date('2017-09-20'),
    org: org.plantTherapy,
    name: 'Lemon Deal',
    category: category.landingPage,
    // preview: '',
    // screenshots: [],
    tags: [skill.html, skill.css, skill.jQuery, skill.js],
    // description: ['[p]()', '[p]()'],
    license: license.propietary,
  },
  {
    date: new Date('2016-02-22'),
    org: org.pixelPerfectTree,
    name: 'DrLogic',
    category: category.website,
    // preview: '',
    // screenshots: [],
    tags: [skill.bootstrap, skill.rails, skill.scss, skill.jQuery, skill.js],
    // description: ['[p]()', '[p]()'],
    license: license.propietary,
  },
  {
    date: new Date('2016-02-18'),
    org: org.pixelPerfectTree,
    name: 'BPR Bank',
    category: category.website,
    // preview: '',
    // screenshots: [],
    tags: [skill.bootstrap, skill.rails, skill.scss, skill.jQuery, skill.js],
    // description: ['[p]()', '[p]()'],
    link: {
      web: 'https://www.bprbank.com',
    },
    license: license.propietary,
  },
  {
    date: new Date('2015-11-12'),
    org: org.apap,
    name: 'Mineriza a tu Familia',
    category: category.webApp,
    // preview: '',
    // screenshots: [],
    tags: [skill.pug, skill.scss, skill.jQuery, skill.js],
    // description: ['[p]()', '[p]()'],
    license: license.propietary,
  },
  {
    date: new Date('2015-10-23'),
    org: org.presidente,
    name: 'Retrobrindis',
    category: category.webApp,
    // preview: '',
    // screenshots: [],
    tags: [skill.pug, skill.scss, skill.jQuery, skill.js],
    // description: ['[p]()', '[p]()'],
    license: license.propietary,
  },
  {
    date: new Date('2015-12-16'), // TODO summer is not on december maybe june/july/august? not may since carnaval was running on april
    org: org.presidente,
    name: 'Verano 2015',
    category: category.website,
    // preview: '',
    // screenshots: [],
    tags: [skill.pug, skill.scss, skill.jQuery, skill.js],
    // description: ['[p]()', '[p]()'],
    license: license.propietary,
  },
  {
    date: new Date('2015-04-18'),
    org: org.presidente,
    name: 'Carnaval 2015',
    category: category.website,
    // preview: '',
    // screenshots: [],
    tags: [skill.pug, skill.scss, skill.jQuery, skill.js],
    // description: ['[p]()', '[p]()'],
    license: license.propietary,
  },
  {
    date: new Date('2014-06-16'),
    org: org.presidente,
    name: 'Detapa el Coro',
    category: category.webApp,
    // preview: '',
    // screenshots: [],
    tags: [skill.pug, skill.scss, skill.jQuery, skill.js],
    // description: ['[p]()', '[p]()'],
    license: license.propietary,
  },
  {
    date: new Date('2014-10-18'),
    org: org.presidente,
    name: 'Photo Assignmet',
    category: category.webApp,
    // preview: '',
    // screenshots: [],
    tags: [skill.pug, skill.scss, skill.jQuery, skill.js],
    // description: ['[p]()', '[p]()'],
    license: license.propietary,
  },
  {
    date: new Date('2014-01-14'),
    org: org.avante,
    name: 'Descubria',
    category: category.website,
    // preview: '',
    // screenshots: [],
    tags: [skill.html, skill.css, skill.jQuery, skill.js],
    // description: ['[p]()', '[p]()'],
    license: license.propietary,
  },
]
