import org from './obj_org.js'
import category from './obj_category.js'
import skill from './obj_skill.js'
import license from './obj_license.js'

export default [
  {
    date: new Date('2026-06-06'),
    org: org.rama,
    name: 'Teyin',
    category: category.androidApp,
    preview: 'https://github.com/rama-io/teyin/raw/master/docs/img/teyin_header_1200x630.svg',
    screenshots: [
      'https://raw.githubusercontent.com/rama-io/teyin/master/fastlane/metadata/android/en-US/images/phoneScreenshots/1.png',
      'https://raw.githubusercontent.com/rama-io/teyin/master/fastlane/metadata/android/en-US/images/phoneScreenshots/2.png',
      'https://raw.githubusercontent.com/rama-io/teyin/master/fastlane/metadata/android/en-US/images/phoneScreenshots/3.png',
    ],
    tags: [skill.kotlin],
    description: [
      '[p](**Teyin** is a lightweight, privacy-first **File manager** designed for speed, and simplicity.)',
      '[p](Built entirely in native **Kotlin**, Teyin runs fully **on-device** and avoids tracking.)',
    ],
    link: {
      web: 'https://rama-io.github.io/teyin.html',
      github: 'https://github.com/rama-io/teyin',
      fdroid: 'https://f-droid.org/app/com.rama.teyin',
      obtanium:
        'https://apps.obtainium.imranr.dev/redirect?r=obtainium://add/https://github.com/rama-io/teyin',
    },
    license: license.gplv3,
  },
  {
    date: new Date('2026-04-25'),
    org: org.rama,
    name: 'Tūī',
    category: category.androidApp,
    preview:
      'https://raw.githubusercontent.com/rama-io/tui/master/docs/img/tui_header_1200x630.svg',
    screenshots: [
      'https://raw.githubusercontent.com/rama-io/tui/master/fastlane/metadata/android/en-US/images/phoneScreenshots/1.png',
      'https://raw.githubusercontent.com/rama-io/tui/master/fastlane/metadata/android/en-US/images/phoneScreenshots/2.png',
      'https://raw.githubusercontent.com/rama-io/tui/master/fastlane/metadata/android/en-US/images/phoneScreenshots/3.png',
    ],
    tags: [skill.kotlin],
    description: [
      '[p](**Tūī** is a minimal, privacy-first **local music player** that skips metadata entirely. What you see is exactly what you name, no hidden tags, no surprises.)',
      '[p](Built entirely in native **Kotlin**, Tūī runs fully **on-device**, avoids tracking, no internet access, and no external APIs.)',
    ],
    link: {
      web: 'https://rama-io.github.io/tui.html',
      github: 'https://github.com/rama-io/tui',
      fdroid: 'https://f-droid.org/app/com.rama.tui',
      obtanium:
        'https://apps.obtainium.imranr.dev/redirect?r=obtainium://add/https://github.com/rama-io/tui',
    },
    license: license.gplv3,
  },
  {
    date: new Date('2026-03-07'),
    org: org.rama,
    name: 'Txori',
    category: category.androidApp,
    preview:
      'https://raw.githubusercontent.com/rama-io/txori/main/docs/img/txori_header_1280x630.svg',
    screenshots: [
      'https://raw.githubusercontent.com/rama-io/tui/master/fastlane/metadata/android/en-US/images/phoneScreenshots/1.png',
      'https://raw.githubusercontent.com/rama-io/tui/master/fastlane/metadata/android/en-US/images/phoneScreenshots/2.png',
      'https://raw.githubusercontent.com/rama-io/tui/master/fastlane/metadata/android/en-US/images/phoneScreenshots/3.png',
    ],
    tags: [skill.kotlin],
    description: [
      '[p](**Txori** is a minimal, privacy-first **focus session app** designed to help you stay present and intentional with your time.)',
      '[p](Built entirely in native **Kotlin**, Txori runs fully **on-device**, avoids tracking, no internet access, and no external APIs.)',
    ],
    link: {
      web: 'https://rama-io.github.io/txori.html',
      github: 'https://github.com/rama-io/txori',
      fdroid: 'https://f-droid.org/app/com.rama.txori',
      obtanium:
        'https://apps.obtainium.imranr.dev/redirect?r=obtainium://add/https://github.com/rama-io/txori',
    },
    license: license.gplv3,
  },
  {
    date: new Date('2025-12-19'),
    org: org.rama,
    name: 'Mako',
    category: category.androidApp,
    preview:
      'https://raw.githubusercontent.com/rama-io/mako/master/docs/img/mako_header_1200x630.svg',
    screenshots: [
      'https://raw.githubusercontent.com/rama-io/mako/master/fastlane/metadata/android/en-US/images/phoneScreenshots/1.png',
      'https://raw.githubusercontent.com/rama-io/mako/master/fastlane/metadata/android/en-US/images/phoneScreenshots/2.png',
      'https://raw.githubusercontent.com/rama-io/mako/master/fastlane/metadata/android/en-US/images/phoneScreenshots/3.png',
    ],
    tags: [skill.kotlin],
    description: [
      '[p](**Mako** is a minimal, privacy-first **android launcher** designed for focus, speed, and simplicity.)',
      '[p](Built entirely in native **Kotlin**, Mako runs fully **on-device**, avoids tracking, and keeps distractions to a minimum by emphasizing clarity and intentional interaction.)',
    ],
    link: {
      web: 'https://rama-io.github.io/mako.html',
      github: 'https://github.com/rama-io/mako',
      fdroid: 'https://f-droid.org/app/com.rama.mako',
      obtanium:
        'https://apps.obtainium.imranr.dev/redirect?r=obtainium://add/https://github.com/rama-io/mako',
    },
    license: license.gplv3,
  },
  {
    date: new Date('2024-12-24'),
    org: org.lomdb,
    name: 'LoM DB',
    category: category.website,
    preview: 'https://lomdb.github.io/img/svg/lom_header-draco.svg',
    screenshots: [
      'https://raw.githubusercontent.com/lomdb/lomdb.github.io/master/metadata/0-min.webp',
      'https://raw.githubusercontent.com/lomdb/lomdb.github.io/master/metadata/1-min.webp',
      'https://raw.githubusercontent.com/lomdb/lomdb.github.io/master/metadata/2-min.webp',
    ],
    tags: [skill.webComponents, skill.svg, skill.css, skill.three],
    description: [
      '[p](**LoM DB** is a community-driven database for tracking and exploring merged servers, top players, and timelines across regions.)',
      '[p](This project is built to help players, analysts, and enthusiasts get a clearer view of evolving server data, elite players, and historical merges, all in one place.)',
    ],
    link: {
      web: 'https://lomdb.github.io/',
      github: 'https://github.com/lomdb/lomdb.github.io',
    },
    license: license.gplv3,
  },
  {
    date: new Date('2022-09-01'),
    org: org.teamup,
    name: 'Consumer App',
    category: category.webApp,
    preview: '',
    screenshots: [],
    tags: [skill.vue3, skill.unoCss, skill.storybook],
    description: ['[p]()', '[p]()'],
    license: license.propietary,
  },
  {
    date: new Date('2022-09-01'),
    org: org.teamup,
    name: 'Provider App',
    category: category.webApp,
    preview: '',
    screenshots: [],
    tags: [skill.vue3, skill.unoCss, skill.storybook],
    description: ['[p]()', '[p]()'],
    license: license.propietary,
  },
  {
    date: new Date('2022-09-01'),
    org: org.teamup,
    name: 'DaysmartVueComponents',
    category: category.nodeModule,
    preview: '',
    screenshots: [],
    tags: [skill.vue3, skill.webComponents, skill.unoCss, skill.storybook, skill.vitest],
    description: ['[p]()', '[p]()'],
    license: license.propietary,
  },
  {
    date: new Date('2018-03-01'),
    org: org.enovational,
    name: 'Formability',
    category: category.webApp,
    preview: '',
    screenshots: [],
    tags: [
      skill.vue2,
      skill.rails,
      skill.css,
      skill.typescript,
      skill.bootstrap,
      skill.konva,
      skill.jQuery,
    ],
    description: ['[p]()', '[p]()'],
    link: {
      web: 'https://formability.com',
    },
    license: license.propietary,
  },
  {
    date: new Date('2018-03-01'),
    org: org.enovational,
    name: 'Popkern',
    category: category.nodeModule,
    preview: '',
    screenshots: [],
    tags: [skill.vue2, skill.rails, skill.css, skill.js],
    description: ['[p]()', '[p]()'],
    license: license.propietary,
  },
  {
    date: new Date('2018-03-01'),
    org: org.enovational,
    name: 'Maryland Department of Transportation - MDOT',
    category: category.webApp,
    preview: '',
    screenshots: [],
    tags: [skill.bootstrap, skill.rails, skill.css, skill.jQuery],
    description: ['[p]()', '[p]()'],
    license: license.propietary,
  },
  {
    date: new Date('2018-03-01'),
    org: org.enovational,
    name: 'Vetboard - MDA',
    category: category.webApp,
    preview: '',
    screenshots: [],
    tags: [skill.bootstrap, skill.rails, skill.css, skill.jQuery],
    description: ['[p]()', '[p]()'],
    license: license.propietary,
  },
    {
    date: new Date('2018-03-01'),
    org: org.enovational,
    name: 'Maryland Financial Disclosures - MSEC',
    category: category.webApp,
    preview: '',
    screenshots: [],
    tags: [skill.bootstrap, skill.rails, skill.css, skill.jQuery],
    description: ['[p]()', '[p]()'],
    license: license.propietary,
  },
  {
    date: new Date('2018-03-01'),
    org: org.enovational,
    name: 'Maryland OneStop',
    category: category.webApp,
    preview: '',
    screenshots: [],
    tags: [skill.bootstrap, skill.rails, skill.css, skill.jQuery],
    description: ['[p]()', '[p]()'],
    link: {
      web: 'https://onestop.md.gov/'
    },
    license: license.propietary,
  },
]
