export default {
  rama: 'Rama',
  enovational: 'Enovational',
  teamup: 'TeamUp',
  pixelPerfectTree: 'PixelPerfectTree',
  drLogic: 'DrLogic',
  plantTherapy: 'Plant Therapy',
  vcg: 'VoxelCubeGames',
  capital: 'Capital',
  presidente: 'Presidente',
  descubria: 'Descubria',
  apap: 'APAP',
  avante: 'Avante',
  lomdb: 'LoM DB',
}
